services:
  # Service web (Django)
  - type: web
    name: gestion-comptabilite
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      chmod +x start.sh
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.prod
      - key: DATABASE_URL
        fromDatabase:
          name: gestion-comptable-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-cache
          property: connectionString

  # Service Celery Worker
  - type: worker
    name: celery-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A config worker --loglevel=info
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.prod
      - key: DATABASE_URL
        fromDatabase:
          name: gestion-comptable-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-cache
          property: connectionString

  # Service Celery Beat
  - type: worker
    name: celery-beat
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A config beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.prod
      - key: DATABASE_URL
        fromDatabase:
          name: gestion-comptable-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-cache
          property: connectionString

databases:
  - name: gestion-comptable-db
    databaseName: gestion_comptable
    user: admin

previewsEnabled: true

redis:
  - name: redis-cache
    ipAllowList: [] # Seuls les services internes peuvent se connecter
