services:
  # Service web (Django)
  - type: web
    name: gestion-comptabilite
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      chmod +x start.sh
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.prod
      - key: DATABASE_URL
        fromDatabase:
          name: gestion-comptable-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-cache
          property: internalConnectionString

  # Service Redis (Cache & Broker)
  - type: redis
    name: redis-cache
    plan: free
    ipAllowList: []

databases:
  - name: gestion-comptable-db
    plan: free
