services:
  # Service web (Django)
  - type: web
    name: gestion-comptabilite
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      chmod +x start.sh
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.prod
      - key: DATABASE_URL
        fromDatabase:
          name: gestion-comptable-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-cache
          property: connectionString

  # Service Celery Worker (Nécessite un plan payant sur Render)
  - type: worker
    name: celery-worker
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A config worker --loglevel=info
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.prod
      - key: DATABASE_URL
        fromDatabase:
          name: gestion-comptable-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-cache
          property: connectionString

  # Service Celery Beat (Nécessite un plan payant sur Render)
  - type: worker
    name: celery-beat
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A config beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.prod
      - key: DATABASE_URL
        fromDatabase:
          name: gestion-comptable-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-cache
          property: connectionString

  # Service Redis (Cache & Broker)
  - type: redis
    name: redis-cache
    plan: free
    ipAllowList: [] # Seuls les services internes de ce blueprint peuvent se connecter

databases:
  - name: gestion-comptable-db
    plan: free
